#!/bin/sh

# Libraries to compile with
LIBS="-lgmp"

echo "Compiling with ${LIBS}..."

# Remove old server exe
if [ -e "server" ]; then
	rm -rf server
fi

# Compile new server exe
if [ -e "server.c" ]; then
	gcc -o server server.c "${LIBS}"
fi

# Remove old client server exe
if [ -e "client" ]; then
	rm -rf client
fi

# Compile new client exe
if [ -e "client.c" ]; then
	gcc -o client client.c "${LIBS}"
fi

#gcc -o test main.c
